# .github/workflows/deploy-theme.yml
name: Deploy Zorvek theme (SCP + password)

on:
  push:
    branches: [ main ]
    paths:
      - 'wp-content/themes/Zorvek/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          source: "wp-content/themes/Zorvek/*"
          target: "/home/dh_ampjbk/walkerwonderstudio.com/wp-content/themes/Zorvek/"
